export const stealthTheme = {
  light: {
    background: "hsl(var(--color-background))",
    foreground: "hsl(var(--color-primary))",
    card: "hsl(var(--color-surface))",
    cardForeground: "hsl(var(--color-primary))",
    popover: "hsl(var(--color-surface))",
    popoverForeground: "hsl(var(--color-primary))",
    primary: "hsl(var(--color-primary))",
    primaryForeground: "hsl(var(--color-background))",
    secondary: "hsl(var(--color-accent))",
    secondaryForeground: "hsl(var(--color-primary))",
    muted: "hsl(var(--color-muted))",
    mutedForeground: "hsl(var(--color-primary))",
    accent: "hsl(var(--color-accent))",
    accentForeground: "hsl(var(--color-primary))",
    destructive: "#991b1b",
    destructiveForeground: "hsl(var(--color-primary))",
    border: "hsl(var(--color-border))",
    input: "hsl(var(--color-border))",
    ring: "hsl(var(--color-primary))",
  },
  dark: {
    background: "hsl(var(--color-background))",
    foreground: "hsl(var(--color-primary))",
    card: "hsl(var(--color-surface))",
    cardForeground: "hsl(var(--color-primary))",
    popover: "hsl(var(--color-surface))",
    popoverForeground: "hsl(var(--color-primary))",
    primary: "hsl(var(--color-primary))",
    primaryForeground: "hsl(var(--color-background))",
    secondary: "hsl(var(--color-accent))",
    secondaryForeground: "hsl(var(--color-primary))",
    muted: "hsl(var(--color-muted))",
    mutedForeground: "hsl(var(--color-primary))",
    accent: "hsl(var(--color-accent))",
    accentForeground: "hsl(var(--color-primary))",
    destructive: "#991b1b",
    destructiveForeground: "hsl(var(--color-primary))",
    border: "hsl(var(--color-border))",
    input: "hsl(var(--color-border))",
    ring: "hsl(var(--color-primary))",
  },
  radius: "0", // Sharp corners
}
